define: DUK_USE_SYMBOL_BUILTIN
introduced: 2.0.0
default: false
tags:
  - ecmascript
  - ecmascript6
description: >
  Provide ES6 Symbol built-ins (experimental in Duktape 2.0.0).

  Even with the built-ins disabled, symbols created by C code are still
  supported.
